Repository deutsche-nationalbibliothek/pica-rs, pull requests merged in 2022-10, with the labels that each got.

#494 Allow `select` command to read from multiple files
  src/bin/pica/commands/select.rs
  tests/pica/select.rs
Labels: enhancement

#495 Add `--append` option to `select` command
  src/bin/pica/commands/select.rs
  tests/pica/select.rs
Labels: enhancement

#497 Add Apache Arrow format for allow-/deny-lists
  Cargo.toml
  src/bin/pica/common.rs
  tests/data/allow_list.arrow
  tests/data/deny_list.arrow
  tests/pica/filter.rs
Labels: enhancement

#498 Improve `invalid` performance
  Cargo.toml
  src/bin/pica/commands/invalid.rs
Labels: enhancement

#500 Document `invalid` command
  docs/book/src/de/SUMMARY.md
  docs/book/src/de/guide/cmds/invalid.md
Labels: documentation

#502 Add wget to install instruction for Ubuntu
  docs/book/src/de/guide/installation.md
Labels: documentation

#521 Add `RecordRef::write_to` function
  pica-record/CHANGELOG.md
  pica-record/src/record.rs
Labels: enhancement

#522 Use `BufReadExt` to process records (`invalid`)
  CHANGELOG.md
  src/bin/pica/commands/invalid.rs
  src/bin/pica/main.rs
  src/bin/pica/util.rs
Labels: enhancement

#525 Add long help (`invalid`)
  CHANGELOG.md
  src/bin/pica/commands/invalid.rs
  src/bin/pica/main.rs
Labels: enhancement

#528 Add `ByteRecord` writer API
  pica-record/CHANGELOG.md
  pica-record/Cargo.toml
  pica-record/src/io/mod.rs
  pica-record/src/io/writer.rs
  pica-record/src/record.rs
Labels: enhancement

#530 Add `raw_data` field (`ByteRecord`)
  pica-record/CHANGELOG.md
  pica-record/src/record.rs
Labels: enhancement

#531 Fix wrong assert expression (`WriterBuilder`)
  pica-record/CHANGELOG.md
  pica-record/src/io/writer.rs
Labels: bug

#532 Improve performance of `cat` command
  CHANGELOG.md
  src/bin/pica/commands/cat.rs
  tests/pica/cat.rs
Labels: enhancement

#536 Update CLI docs (`cat`)
  src/bin/pica/commands/cat.rs
  src/bin/pica/main.rs
Labels: documentation

#537 Stabilize `cat` command
  CHANGELOG.md
  README.md
  docs/book/src/de/guide/cmds/cat.md
Labels: documentation
