Repository deutsche-nationalbibliothek/pica-rs, pull requests merged in 2023-08, with the labels that each got.

#680 Fix cargo-upgrades job
  .github/workflows/daily.yml
Labels: bug

#681 Fix typo
  docs/book/src/referenz/kommandos/filter.md
Labels: documentation, C-filter

#685 Deprecate outdated path syntax
  pica-path/src/lib.rs
  pica-toolkit/tests/snapshot/frequency/023-frequency-subfield-matcher.toml
  pica-toolkit/tests/snapshot/frequency/024-frequency-subfield-matcher-ci.toml
  pica-toolkit/tests/snapshot/frequency/586-frequency-translit-path1.toml
  pica-toolkit/tests/snapshot/frequency/586-frequency-translit-path2.toml
  pica-toolkit/tests/snapshot/select/586-select-translit-selector1.toml
  pica-toolkit/tests/snapshot/select/586-select-translit-selector2.toml
  pica-toolkit/tests/snapshot/select/605-false-positives-regex.toml
Labels: breaking-change

#686 Adapt select/frequency to new path struct
  pica-matcher/src/subfield_matcher.rs
  pica-matcher/src/tag_matcher.rs
  pica-path/src/lib.rs
  pica-select/src/lib.rs
  pica-toolkit/src/commands/frequency.rs
  pica-toolkit/tests/snapshot/frequency/027-frequency-multiple-cols.in/dump.dat.gz
  pica-toolkit/tests/snapshot/frequency/027-frequency-multiple-cols.toml
Labels: enhancement, C-select, C-frequency, breaking-change

#692 Fix cargo install command
  README.md
Labels: documentation

#691 Add `partition` documentation
  docs/book/src/SUMMARY.md
  docs/book/src/referenz/kommandos/index.md
  docs/book/src/referenz/kommandos/partition.md
  pica-toolkit/tests/snapshot.rs
Labels: documentation, C-partition

#693 Add progress bar
  CHANGELOG.md
  docs/book/src/referenz/kommandos/cat.md
  docs/book/src/referenz/kommandos/convert.md
  docs/book/src/referenz/kommandos/count.md
  docs/book/src/referenz/kommandos/filter.md
  docs/book/src/referenz/kommandos/frequency.md
  docs/book/src/referenz/kommandos/hash.md
  docs/book/src/referenz/kommandos/invalid.md
  docs/book/src/referenz/kommandos/partition.md
  docs/book/src/referenz/kommandos/print.md
  docs/book/src/referenz/kommandos/slice.md
  docs/book/src/referenz/kommandos/split.md
  pica-toolkit/Cargo.toml
  pica-toolkit/src/commands/cat.rs
  pica-toolkit/src/commands/convert/mod.rs
  pica-toolkit/src/commands/count.rs
  pica-toolkit/src/commands/filter.rs
  pica-toolkit/src/commands/frequency.rs
  pica-toolkit/src/commands/hash.rs
  pica-toolkit/src/commands/invalid.rs
  pica-toolkit/src/commands/partition.rs
  pica-toolkit/src/commands/print.rs
  pica-toolkit/src/commands/sample.rs
  pica-toolkit/src/commands/select.rs
  pica-toolkit/src/commands/slice.rs
  pica-toolkit/src/commands/split.rs
  pica-toolkit/src/main.rs
  pica-toolkit/src/progress.rs
Labels: enhancement

#694 Add `explode` command
  docs/book/src/SUMMARY.md
  docs/book/src/referenz/kommandos/explode.in/COPY.dat.gz
  docs/book/src/referenz/kommandos/explode.md
  docs/book/src/referenz/kommandos/index.md
  pica-record/src/field.rs
  pica-record/src/tag.rs
  pica-toolkit/src/commands/explode.rs
  pica-toolkit/src/commands/mod.rs
  pica-toolkit/src/config.rs
  pica-toolkit/src/main.rs
  pica-toolkit/tests/snapshot.rs
  pica-toolkit/tests/snapshot/explode/000-explode-main.in/COPY.dat.gz
  pica-toolkit/tests/snapshot/explode/000-explode-main.out/main.dat
  pica-toolkit/tests/snapshot/explode/000-explode-main.toml
  pica-toolkit/tests/snapshot/explode/001-explode-local.in/COPY.dat.gz
  pica-toolkit/tests/snapshot/explode/001-explode-local.out/local.dat
  pica-toolkit/tests/snapshot/explode/001-explode-local.toml
  pica-toolkit/tests/snapshot/explode/002-explode-copy.in/COPY.dat.gz
  pica-toolkit/tests/snapshot/explode/002-explode-copy.out/copy.dat
  pica-toolkit/tests/snapshot/explode/002-explode-copy.toml
  pica-toolkit/tests/snapshot/explode/003-explode-where.in/COPY.dat.gz
  pica-toolkit/tests/snapshot/explode/003-explode-where.out/1.dat
  pica-toolkit/tests/snapshot/explode/003-explode-where.toml
Labels: enhancement

#695 Improve `explode` documentation
  docs/book/src/referenz/kommandos/explode.md
  docs/book/src/referenz/kommandos/index.md
Labels: documentation
