Repository deutsche-nationalbibliothek/pica-rs, pull requests merged in 2025-04, with the labels that each got.

#951 ci: change path to `deny.toml`
  .deny.toml
  .github/workflows/daily.yml
  .github/workflows/rust.yml
Labels: maintenance

#931 feat: add contains (set) matcher
  Cargo.toml
  crates/pica-cli/Cargo.toml
  crates/pica-cli/tests/filter/contains.rs
  crates/pica-cli/tests/filter/mod.rs
  docs/book/_quarto.yml
  docs/book/filter.qmd
  src/matcher/subfield/mod.rs
  src/matcher/subfield/parser.rs
Labels: enhancement

#952 docs: fix minor errors
  docs/book/tutorials/beginner.qmd
Labels: docs

#929 feat(describe): add `describe` command
  crates/pica-cli/Cargo.toml
  crates/pica-cli/src/cli.rs
  crates/pica-cli/src/commands/describe.rs
  crates/pica-cli/src/commands/mod.rs
  crates/pica-cli/src/main.rs
  crates/pica-cli/tests/describe/mod.rs
  crates/pica-cli/tests/integration.rs
  docs/book/_quarto.yml
  docs/book/commands/describe.qmd
Labels: enhancement

#955 docs(check): minor changes
  docs/book/commands/check.qmd
Labels: docs
